name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]  # Updated to use armv7 instead of arm/v7

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all  # Automatically supports all platforms

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/${{ matrix.arch }}
          tags: |
            dsmithson/printersmtpserver:latest
            dsmithson/printersmtpserver:${{ matrix.arch }}-latest
            dsmithson/printersmtpserver:${{ matrix.arch }}-${{ env.SHORT_SHA }}
          push: ${{ github.event_name != 'pull_request' }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest for latest
        run: |
          docker manifest create dsmithson/printersmtpserver:latest \
            --amend dsmithson/printersmtpserver:amd64-latest \
            --amend dsmithson/printersmtpserver:arm64-latest \
            --amend dsmithson/printersmtpserver:armv7-latest
          docker manifest push dsmithson/printersmtpserver:latest

      - name: Create and push manifest for commit SHA
        run: |
          docker manifest create dsmithson/printersmtpserver:${{ env.SHORT_SHA }} \
            --amend dsmithson/printersmtpserver:amd64-${{ env.SHORT_SHA }} \
            --amend dsmithson/printersmtpserver:arm64-${{ env.SHORT_SHA }} \
            --amend dsmithson/printersmtpserver:armv7-${{ env.SHORT_SHA }}
          docker manifest push dsmithson/printersmtpserver:${{ env.SHORT_SHA }}
