name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, arm32]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            your-dockerhub-username/printersmtpserver:latest
            your-dockerhub-username/printersmtpserver:${{ env.SHORT_SHA }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Create and push manifest
        if: github.event_name != 'pull_request'
        run: |
          docker manifest create your-dockerhub-username/printersmtpserver:latest \
            --amend your-dockerhub-username/printersmtpserver:amd64 \
            --amend your-dockerhub-username/printersmtpserver:arm64 \
            --amend your-dockerhub-username/printersmtpserver:arm/v7
          docker manifest push your-dockerhub-username/printersmtpserver:latest
          docker manifest create your-dockerhub-username/printersmtpserver:${{ env.SHORT_SHA }} \
            --amend your-dockerhub-username/printersmtpserver:amd64 \
            --amend your-dockerhub-username/printersmtpserver:arm64 \
            --amend your-dockerhub-username/printersmtpserver:arm/v7
          docker manifest push your-dockerhub-username/printersmtpserver:${{ env.SHORT_SHA }}
